### ISSUE TITLE
Sample app crash on rotation

### ISSUE THREAD

**Issue by mykola-dev** [jakubkinst/Android-ViewModelBinding#8]
Steps to reproduce:
1. Run the app
2. Rotate device

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                                          at cz.kinst.jakub.viewmodelbinding.ViewModelBindingHelper.getViewModelIdFieldName(ViewModelBindingHelper.java:215)
                                                                                          at cz.kinst.jakub.viewmodelbinding.ViewModelBindingHelper.onCreate(ViewModelBindingHelper.java:72)
                                                                                          at cz.kinst.jakub.viewmodelbinding.ViewModelActivity.onCreate(ViewModelActivity.java:70)
```

**Comment by jakubkinst** [comment]
Sorry, that were unreleased changes being merged to `master` too early. Fixed on `master`.

**Comment by mykola-dev** [comment]
Bu i'm using latest code from master. Still crashes. Any advice?

**Comment by jakubkinst** [comment]
After you created the issue, I have reverted `master` to an earlier commit. Can you make sure your `master` is on this commit: https://github.com/jakubkinst/Android-ViewModelBinding/commit/e546d61b9ee7e3aeb548de0abbbb46c847f43a36 ? Thanks

**Comment by mykola-dev** [comment]
Yes, i made reset to this commit and now it works ok. Thanks
